In [1]:
import pandas as pd
import numpy as np

In [2]:
df1=pd.DataFrame({"key":["a","b","c","c","d","e"],
                      "num1":range(6)})
df2=pd.DataFrame({"key":["b","c","e","f"],
                  "num2":range(4)})
print(df1)
print(df2)

  key  num1
0   a     0
1   b     1
2   c     2
3   c     3
4   d     4
5   e     5
  key  num2
0   b     0
1   c     1
2   e     2
3   f     3


In [4]:
pd.merge(df1,df2) #merges the common datas

key  num1  num2
0   b     1     0
1   c     2     1
2   c     3     1
3   e     5     2

In [5]:
pd.merge(df1,df2, on="key")

key  num1  num2
0   b     1     0
1   c     2     1
2   c     3     1
3   e     5     2

In [11]:
df3=pd.DataFrame({"key1":["a","b","c","c","d","e"],
                      "num1":range(6)})
df4=pd.DataFrame({"key2":["b","c","e","f"],
                  "num2":range(4)})
print(df3)
print(df4)

  key1  num1
0    a     0
1    b     1
2    c     2
3    c     3
4    d     4
5    e     5
  key2  num2
0    b     0
1    c     1
2    e     2
3    f     3


In [14]:
pd.merge(df3,df4,left_on="key1", right_on="key2") #underdtand this as union

key1  num1 key2  num2
0    b     1    b     0
1    c     2    c     1
2    c     3    c     1
3    e     5    e     2

In [15]:
pd.merge(df1, df2, how="outer") #all the value are shown

key  num1  num2
0   a   0.0   NaN
1   b   1.0   0.0
2   c   2.0   1.0
3   c   3.0   1.0
4   d   4.0   NaN
5   e   5.0   2.0
6   f   NaN   3.0

In [16]:
pd.merge(df1, df2, how="left")  #left ko table intact

key  num1  num2
0   a     0   NaN
1   b     1   0.0
2   c     2   1.0
3   c     3   1.0
4   d     4   NaN
5   e     5   2.0

In [17]:
pd.merge(df1, df2, how="right")  #merge from right garda right ko table intact

key  num1  num2
0   b   1.0     0
1   c   2.0     1
2   c   3.0     1
3   e   5.0     2
4   f   NaN     3

In [19]:
pd.merge(df1, df2, how="inner")   #intersection

key  num1  num2
0   b     1     0
1   c     2     1
2   c     3     1
3   e     5     2

In [24]:
right=pd.DataFrame([[1,2],[3,4],[5,6]],
                  index=["a","c","d"],
                  columns=["Tom","Tim"])
left=pd.DataFrame([[7,8],[9,10],[11,12],[13,14]],
                  index=["a","b","e","f"],
                  columns=["Sam","Kim"])

print(right)
print(left)

   Tom  Tim
a    1    2
c    3    4
d    5    6
   Sam  Kim
a    7    8
b    9   10
e   11   12
f   13   14


In [27]:
pd.merge(right, left,
        right_index=True,
        left_index=True,
        how="outer")

Tom  Tim   Sam   Kim
a  1.0  2.0   7.0   8.0
b  NaN  NaN   9.0  10.0
c  3.0  4.0   NaN   NaN
d  5.0  6.0   NaN   NaN
e  NaN  NaN  11.0  12.0
f  NaN  NaN  13.0  14.0

In [28]:
left.join(right)

Sam  Kim  Tom  Tim
a    7    8  1.0  2.0
b    9   10  NaN  NaN
e   11   12  NaN  NaN
f   13   14  NaN  NaN

In [33]:
data=pd.DataFrame([[1,2],[5,7],[9,11]],index=["a","b","f"],columns=["Alex","Keta"])
data

Alex  Keta
a     1     2
b     5     7
f     9    11

In [35]:
left.join([right, data]) #inner join by default

Sam   Kim  Tom  Tim  Alex  Keta
a   7.0   8.0  1.0  2.0   1.0   2.0
b   9.0  10.0  NaN  NaN   5.0   7.0
e  11.0  12.0  NaN  NaN   NaN   NaN
f  13.0  14.0  NaN  NaN   9.0  11.0

In [37]:
#concatenation
seq=np.arange(20).reshape(4,5)
seq

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [38]:
np.concatenate(seq)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [39]:
np.concatenate([seq,seq], axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [40]:
np.concatenate([seq,seq], axis=1)

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 15, 16, 17, 18, 19]])

In [41]:
data1=pd.Series([0,1], index=['a','b'])
data2=pd.Series([2,3,4], index=['c','d',"e"])
data3=pd.Series([5,6], index=['f','g'])
print(data1)
print(data2)
print(data3)

a    0
b    1
dtype: int64
c    2
d    3
e    4
dtype: int64
f    5
g    6
dtype: int64


In [44]:
np.concatenate([data1, data2, data3])

array([0, 1, 2, 3, 4, 5, 6], dtype=int64)

In [43]:
pd.concat([data1, data2, data3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [45]:
pd.concat([data1, data2, data3], axis=1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [48]:
data4=pd.Series([10,11,12], index=['a','b','c'])
pd.concat([data1, data4], axis=1, join="inner")

0   1
a  0  10
b  1  11

In [51]:
x=pd.concat([data1, data2, data4], keys=["one", "two", "three"])
x

one    a     0
       b     1
two    c     2
       d     3
       e     4
three  a    10
       b    11
       c    12
dtype: int64

In [61]:
data1=pd.DataFrame(np.random.randn(3,4), 
                   columns=['a','b','c','d'])
data2=pd.DataFrame(np.random.randn(2,3), 
                   columns=['b','d','f'])
print(data1)
print(data2)

          a         b         c         d
0 -0.412980  0.402432  0.944954 -0.225101
1  0.115301  1.194652  0.114359 -1.716742
2 -0.520641  1.848460 -1.578672 -0.703497
          b         d         f
0  0.639850  0.214864 -0.938426
1  2.206608  0.231771  0.094010


In [64]:
pd.concat([data1, data2])

a         b         c         d         f
0 -0.412980  0.402432  0.944954 -0.225101       NaN
1  0.115301  1.194652  0.114359 -1.716742       NaN
2 -0.520641  1.848460 -1.578672 -0.703497       NaN
0       NaN  0.639850       NaN  0.214864 -0.938426
1       NaN  2.206608       NaN  0.231771  0.094010

In [65]:
pd.concat([data1, data2], ignore_index=True)

a         b         c         d         f
0 -0.412980  0.402432  0.944954 -0.225101       NaN
1  0.115301  1.194652  0.114359 -1.716742       NaN
2 -0.520641  1.848460 -1.578672 -0.703497       NaN
3       NaN  0.639850       NaN  0.214864 -0.938426
4       NaN  2.206608       NaN  0.231771  0.094010

In [68]:
!pip install nycflights13

  Using cached nycflights13-0.0.3.tar.gz (8.7 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for nycflights13: filename=nycflights13-0.0.3-py3-none-any.whl size=8732736 sha256=21d74e0541edcf91eb890e14e87af1f5b0a445e15c5b7712ad750c1f57d32d8b
  Stored in directory: c:\users\user\appdata\local\pip\cache\wheels\45\69\2d\ef1024b231256499d8d8d414588fab2ea9bea42529be5c9c64
Successfully built nycflights13


In [69]:
import pandas as pd


In [75]:
from nycflights13 import flights
from nycflights13 import airlines
from nycflights13 import airports

In [76]:
flights.head()

year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
0  2013      1    1     517.0             515        2.0     830.0   
1  2013      1    1     533.0             529        4.0     850.0   
2  2013      1    1     542.0             540        2.0     923.0   
3  2013      1    1     544.0             545       -1.0    1004.0   
4  2013      1    1     554.0             600       -6.0     812.0   

   sched_arr_time  arr_delay carrier  flight tailnum origin dest  air_time  \
0             819       11.0      UA    1545  N14228    EWR  IAH     227.0   
1             830       20.0      UA    1714  N24211    LGA  IAH     227.0   
2             850       33.0      AA    1141  N619AA    JFK  MIA     160.0   
3            1022      -18.0      B6     725  N804JB    JFK  BQN     183.0   
4             837      -25.0      DL     461  N668DN    LGA  ATL     116.0   

   distance  hour  minute             time_hour  
0      1400     5      15  2013-01-01T10:00:00Z  
1      1416     5      29  2013-01-01T10:00:00Z  
2      1089     5      40  2013-01-01T10:00:00Z  
3      1576     5      45  2013-01-01T10:00:00Z  
4       762     6       0  2013-01-01T11:00:00Z

In [77]:
airlines.head()

carrier                    name
0      9E       Endeavor Air Inc.
1      AA  American Airlines Inc.
2      AS    Alaska Airlines Inc.
3      B6         JetBlue Airways
4      DL    Delta Air Lines Inc.

In [78]:
airports.head()

faa                           name        lat        lon   alt  tz dst  \
0  04G              Lansdowne Airport  41.130472 -80.619583  1044  -5   A   
1  06A  Moton Field Municipal Airport  32.460572 -85.680028   264  -6   A   
2  06C            Schaumburg Regional  41.989341 -88.101243   801  -6   A   
3  06N                Randall Airport  41.431912 -74.391561   523  -5   A   
4  09J          Jekyll Island Airport  31.074472 -81.427778    11  -5   A   

              tzone  
0  America/New_York  
1   America/Chicago  
2   America/Chicago  
3  America/New_York  
4  America/New_York

In [82]:
#airline with high delay deaprture
delayed_flights=flights[flights['dep_delay']>0].groupby('carrier').size().reset_index(name="num_delay")
delayed_flights

carrier  num_delay
0       9E       7063
1       AA      10162
2       AS        226
3       B6      21445
4       DL      15241
5       EV      23139
6       F9        341
7       FL       1654
8       HA         69
9       MQ       8031
10      OO          9
11      UA      27261
12      US       4775
13      VX       2225
14      WN       6558
15      YV        233

In [87]:
delayed_flights.merge(airlines,on="carrier", how="left")

carrier  num_delay                         name
0       9E       7063            Endeavor Air Inc.
1       AA      10162       American Airlines Inc.
2       AS        226         Alaska Airlines Inc.
3       B6      21445              JetBlue Airways
4       DL      15241         Delta Air Lines Inc.
5       EV      23139     ExpressJet Airlines Inc.
6       F9        341       Frontier Airlines Inc.
7       FL       1654  AirTran Airways Corporation
8       HA         69       Hawaiian Airlines Inc.
9       MQ       8031                    Envoy Air
10      OO          9        SkyWest Airlines Inc.
11      UA      27261        United Air Lines Inc.
12      US       4775              US Airways Inc.
13      VX       2225               Virgin America
14      WN       6558       Southwest Airlines Co.
15      YV        233           Mesa Airlines Inc.

In [88]:
flights = flights[flights['dep_delay'] > 0] # filter for delays
carrier_delay_count = flights.groupby('carrier').size().reset_index(name='num_delay') # count the delays by carrier
max_delay_carrier = carrier_delay_count[carrier_delay_count['num_delay'] == carrier_delay_count['num_delay'].max()] # find the carrier with the most delays
most_delayed_airline = pd.merge(max_delay_carrier, airlines, on='carrier', how='left')['name'] # join with airlines table and select the name of the most delayed airline

In [89]:
most_delayed_airline

0    United Air Lines Inc.
Name: name, dtype: object

In [91]:
flights.groupby('dest').agg(mean_delay=('arr_delay','mean'))

mean_delay
dest            
ABQ    26.460870
ACK    31.950617
ALB    44.000000
ANC     0.166667
ATL    41.692537
...          ...
TPA    34.570677
TUL    64.970414
TVC    62.028571
TYS    62.510714
XNA    45.185039

[103 rows x 1 columns]

In [92]:
flights.groupby('dest').agg(mean_delay=('arr_delay'
                                        , 'mean')).reset_index().query('mean_delay == mean_delay.min()')

dest  mean_delay
75  PSP   -9.333333

In [95]:
flights.groupby('dest').agg(mean_delay=('arr_delay', 'mean')).reset_index()\
    .query('mean_delay == mean_delay.min()').merge(airports, left_on='dest', right_on='faa', how='left')

dest  mean_delay  faa               name        lat         lon  alt  tz  \
0  PSP   -9.333333  PSP  Palm Springs Intl  33.829667 -116.506694  477  -8   

  dst                tzone  
0   A  America/Los_Angeles

In [97]:
flights.groupby('dest').agg(mean_delay=('arr_delay', 'mean')).reset_index()\
    .query('mean_delay == mean_delay.min()')\
    .merge(airports, left_on='dest', right_on='faa')\
    .loc[:, ['name']]

name
0  Palm Springs Intl